name: flutter_artist_core
description: The core foundational engineering engine of the FlutterArtist ecosystem. It encapsulates enterprise-grade generic collection structures, resilient JSON validation error extractors, flexible pagination models, and decoupled architecture adapter gateways for authentication, overlays, and notification service layers.
version: 3.1.0
resolution: workspace
homepage: https://o7planning.github.io
#repository:

environment:
  sdk: ^3.7.2
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: