name: flutter_artist_core
description: "Flutter Artist Core."
version: 0.9.1
resolution: workspace
homepage: https://o7planning.github.io
#repository:

environment:
  sdk: ^3.7.2
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: